config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :orders
  resources :shops
  resources :admin_reports
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_report.rb
class AdminReport < MasterRecord
end

app/controllers/admin_reports_controller.rb
class AdminReportsController < ApplicationController
  before_action :set_admin_report, only: [:show, :edit, :update, :destroy]

  # GET /admin_reports
  # GET /admin_reports.json
  def index
    @admin_reports = AdminReport.all
  end

  # GET /admin_reports/1
  # GET /admin_reports/1.json
  def show
  end

  # GET /admin_reports/new
  def new
    @admin_report = AdminReport.new
  end

  # GET /admin_reports/1/edit
  def edit
  end

  # POST /admin_reports
  # POST /admin_reports.json
  def create
    @admin_report = AdminReport.new(admin_report_params)

    respond_to do |format|
      if @admin_report.save
        format.html { redirect_to @admin_report, notice: 'Admin report was successfully created.' }
        format.json { render :show, status: :created, location: @admin_report }
      else
        format.html { render :new }
        format.json { render json: @admin_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_reports/1
  # PATCH/PUT /admin_reports/1.json
  def update
    respond_to do |format|
      if @admin_report.update(admin_report_params)
        format.html { redirect_to @admin_report, notice: 'Admin report was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_report }
      else
        format.html { render :edit }
        format.json { render json: @admin_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_reports/1
  # DELETE /admin_reports/1.json
  def destroy
    @admin_report.destroy
    respond_to do |format|
      format.html { redirect_to admin_reports_url, notice: 'Admin report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_report
      @admin_report = AdminReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_report_params
      params.fetch(:admin_report, {})
    end
end

app/helpers/admin_reports_helper.rb
module AdminReportsHelper
end

app/views/admin_reports/_form.html.erb
<%= form_with(model: admin_report, local: true) do |form| %>
  <% if admin_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_report.errors.count, "error") %> prohibited this admin_report from being saved:</h2>

      <ul>
      <% admin_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin_reports/edit.html.erb
<h1>Editing Admin Report</h1>

<%= render 'form', admin_report: @admin_report %>

<%= link_to 'Show', @admin_report %> |
<%= link_to 'Back', admin_reports_path %>

app/views/admin_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Reports</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_reports.each do |admin_report| %>
      <tr>
        <td><%= link_to 'Show', admin_report %></td>
        <td><%= link_to 'Edit', edit_admin_report_path(admin_report) %></td>
        <td><%= link_to 'Destroy', admin_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Report', new_admin_report_path %>

app/views/admin_reports/new.html.erb
<h1>New Admin Report</h1>

<%= render 'form', admin_report: @admin_report %>

<%= link_to 'Back', admin_reports_path %>

app/views/admin_reports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_report_path(@admin_report) %> |
<%= link_to 'Back', admin_reports_path %>